# Generated by Django 3.2.6 on 2021-08-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='title',
            field=models.CharField(choices=[('Gen.', 'Gen.'), ('Mrs.', 'Mrs.'), ('Rev.', 'Rev.'), ('Ms.', 'Ms.'), ('Prof.', 'Prof.'), ('Sen.', 'Sen.'), ('Mr.', 'Mr.'), ('Dr.', 'Dr.')], max_length=60, null=True),
        ),
    ]
