# Generated by Django 3.2.6 on 2021-08-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0002_profiles_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='title',
            field=models.CharField(choices=[('Mr.', 'Mr.'), ('Dr.', 'Dr.'), ('Gen.', 'Gen.'), ('Rev.', 'Rev.'), ('Prof.', 'Prof.'), ('Sen.', 'Sen.'), ('Ms.', 'Ms.'), ('Mrs.', 'Mrs.')], max_length=60, null=True),
        ),
    ]
