# Generated by Django 3.2.6 on 2021-08-29 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0003_alter_profiles_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='title',
            field=models.CharField(choices=[('Prof.', 'Prof.'), ('Sen.', 'Sen.'), ('Rev.', 'Rev.'), ('Mrs.', 'Mrs.'), ('Mr.', 'Mr.'), ('Ms.', 'Ms.'), ('Dr.', 'Dr.'), ('Gen.', 'Gen.')], max_length=60, null=True),
        ),
    ]
