# Generated by Django 3.2.7 on 2021-09-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0005_auto_20210906_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Sen.', 'Sen.'), ('Prof.', 'Prof.'), ('Rev.', 'Rev.'), ('Dr.', 'Dr.'), ('Ms.', 'Ms.'), ('Gen.', 'Gen.')], max_length=60, null=True),
        ),
    ]
