# Generated by Django 3.1.5 on 2021-09-07 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoclasses',
            name='course_number',
            field=models.IntegerField(),
        ),
    ]
